In [ ]:
import pandas as pd
import numpy as np # Import numpy for np.arange

# Dataframe 1: Online Store Customers
df1_online = pd.DataFrame({
    'CustomerID': np.arange(1, 4), # Added values for CustomerID
    'OnlineSpend': [150, 230, 45]
})

# Dataframe 2: Physical Store Customers
df2_physical = pd.DataFrame({
    'CustomerID': np.arange(3, 6), # Added values for CustomerID
    'InStoreSpend': [310, 75, 410]
})

# Complete master datasets via concatenation
df_online_all = pd.concat([df1_online], ignore_index=True)
df_physical_all = pd.concat([df2_physical], ignore_index=True)

# Option 1: Concatenation by Axis (Side-by-side)
df_axis = pd.concat([df_online_all, df_physical_all], axis=1)
display(df_axis)

# Option 2: Inner Join (Omnichannel Customers)
df_inner = df_online_all.merge(df_physical_all, how='inner')
display(df_inner)

# Option 3: Left Join (All Online Customers)
df_left = df_online_all.merge(df_physical_all, how='left')
display(df_left)

# Option 4: Right Join (All Physical Store Customers)
df_right = df_online_all.merge(df_physical_all, how='right')
display(df_right)

# Sales Registry Dataset Replacement
sales_data = {
    'TransactionID': np.arange(1001, 1006), # Added values for TransactionID
    'Company': ['Logitech', 'Apple', 'Logitech', 'Samsung', 'Apple'],
    'UnitPrice': [50, 1200, 60, 300, 1500], # Added values for UnitPrice
    'Quantity': [3, 1, 2, 4, 2]
}
df_sales = pd.DataFrame(sales_data)
display(df_sales.head(10))

# Feature Engineering: Total Price Calculation
df_sales['TotalPrice'] = df_sales['UnitPrice'] * df_sales['Quantity']
display(df_sales.head(10))

# Value Counts and Summary Statistics
display(df_sales['Company'].value_counts())
display(df_sales.describe())

   CustomerID  OnlineSpend  CustomerID  InStoreSpend
0           1          150           3           310
1           2          230           4            75
2           3           45           5           410

   CustomerID  OnlineSpend  InStoreSpend
0           3           45           310

   CustomerID  OnlineSpend  InStoreSpend
0           1          150           NaN
1           2          230           NaN
2           3           45         310.0

   CustomerID  OnlineSpend  InStoreSpend
0           3         45.0           310
1           4          NaN            75
2           5          NaN           410

   TransactionID   Company  UnitPrice  Quantity
0           1001  Logitech         50         3
1           1002     Apple       1200         1
2           1003  Logitech         60         2
3           1004   Samsung        300         4
4           1005     Apple       1500         2

   TransactionID   Company  UnitPrice  Quantity  TotalPrice
0           1001  Logitech         50         3         150
1           1002     Apple       1200         1        1200
2           1003  Logitech         60         2         120
3           1004   Samsung        300         4        1200
4           1005     Apple       1500         2        3000

Company
Logitech    2
Apple       2
Samsung     1
Name: count, dtype: int64

       TransactionID    UnitPrice  Quantity   TotalPrice
count       5.000000     5.000000  5.000000     5.000000
mean     1003.000000   622.000000  2.400000  1134.000000
std         1.581139   680.382246  1.140175  1171.230123
min      1001.000000    50.000000  1.000000   120.000000
25%      1002.000000    60.000000  2.000000   150.000000
50%      1003.000000   300.000000  2.000000  1200.000000
75%      1004.000000  1200.000000  3.000000  1200.000000
max      1005.000000  1500.000000  4.000000  3000.000000

In [ ]:
import pandas as pd
import numpy as np

data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
display(dframe1)
stacked = dframe1.stack()
display(stacked)

display(stacked.unstack())

series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
display(frame2.unstack())

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN